const CONSTANTES = {
  SCREEN: {
    width: 3556, //(2000 * 16) / 9,
    height: 2000
  },
  // PROJECTILES
  PROJECTILE_RADIUS: 5,
  PROJECTILE_SPEED: 13,
  // PLAYER
  PLAYER_SPEED: 10,
  PLAYER_ROTATION_SPEED: 2,
  PLAYER_RADIUS: 25,
  PLAYER_LIVES: 3,
  PLAYER_RESPAWN_DELAY: 5000,
  PLAYER_INVICIBLE_DELAY: 3000,
  SHOOT_INTERVAL: 500,
  PLAYER_MAX_ROTATION: 10,
  PLAYER_MAX_SPEED: 30,
  // ENEMY
  ENEMY_RADIUS: 25, // has to match enemy.svg file size /2 !
  LEVEL_PROGRESS_PER_KILL: 0, //0.1,
  // BONUS
  BONUS_RADIUS: 10,
  BONUS_SPEED: 8,
  BONUS_SCORE: 10,
  BONUS_PER_NB_KILLS: 20
}

module.exports = CONSTANTES
